### PR TITLE
Ground_Simulation_Support_Module

### PR DESCRIPTION
**Pull request by yingying1968**
1. The "IFF_ASU.csv" has been marked
2. The output file "ASDE-X_Speed.csv" contains the output.
3. The "Gaussian_Plot.py" could visulize the output.
4. Operate the "ASDE-X_History_Speed.py" would give you the average historical speed in the airport.
5. You could modify the Find_Ground_Operation_4.py to get the particular area's speed. One example has been provided.

### CODE REVIEW

**Comment by jmcfarland-swri** [comment]
Thank you for the contribution.  This will require significant re-organization before we can integrate it into para-atm.  Please review our guide to contributing: https://github.com/ymlasu/para-atm/wiki/Contributing.  Some of the main points to consider:

- By placing a directory `Ground_Speed_Upload` in the root of the project, it is not actually part of the source code for para-atm.  All of the code must be within the `paraatm` directory.
- Please carefully review the "Style" section in the contributing guide.  All module (file) and sub-package (directory) names should be lowercase only.
- Please carefully review the "Organization of the Code" section in the guide.  One example structure for you would be to create a directory under `paraatm` called `gss` (short for ground simulation support).  Then place your modules (files) under that directory.
- It should not be necessary to use any `os.system('python')` calls.  All calls to other Python modules should be done internally by importing those modules.
- Most of the code that creates new directories should probably be removed.  The user of the module should be responsible for organizing their directories and telling your module (via function arguments) where they want to read and write files from.  If there are some special circumstances with your module, we can discuss how to address those.

Before you continue, I would encourage to you plan out what the "API" for your module is.  You have many files, but what are the specific functions that users of your module would interact with?  For example, they would probably not interact with `createFolder` (which should probably be removed), but maybe they would interact with `FAA_Parser` and `FAA_Parser.get_flight_plan`?  I suggest that you create a list of only those functions that the user would interact with.  Everything else is "private" (not part of your module's "public API").  Once you have defined this, then you can organize your code to make it clear which functions are private and which are public.  Then, you will want to add documentation (docstrings) for the public functions, so that the users know how to use them (there are many existing examples in para-atm that you can refer to).

Also, some of your files (such as `Reshape_Information_2.py`) do not actually define any functions, so it is unclear what their role is within para-atm.  Potentially these are extraneous and can be removed from your submission.  If they are required by your module, some re-organization will be needed.

Lastly, if you are new to git, I encourage you to read the first three chapters of the Git Book: https://git-scm.com/book/en/v2.

**Comment by yingying1968** [comment]
> Thank you for the contribution. This will require significant re-organization before we can integrate it into para-atm. Please review our guide to contributing: https://github.com/ymlasu/para-atm/wiki/Contributing. Some of the main points to consider:
> 
> * By placing a directory `Ground_Speed_Upload` in the root of the project, it is not actually part of the source code for para-atm.  All of the code must be within the `paraatm` directory.
> * Please carefully review the "Style" section in the contributing guide.  All module (file) and sub-package (directory) names should be lowercase only.
> * Please carefully review the "Organization of the Code" section in the guide.  One example structure for you would be to create a directory under `paraatm` called `gss` (short for ground simulation support).  Then place your modules (files) under that directory.
> * It should not be necessary to use any `os.system('python')` calls.  All calls to other Python modules should be done internally by importing those modules.
> * Most of the code that creates new directories should probably be removed.  The user of the module should be responsible for organizing their directories and telling your module (via function arguments) where they want to read and write files from.  If there are some special circumstances with your module, we can discuss how to address those.
> 
> Before you continue, I would encourage to you plan out what the "API" for your module is. You have many files, but what are the specific functions that users of your module would interact with? For example, they would probably not interact with `createFolder` (which should probably be removed), but maybe they would interact with `FAA_Parser` and `FAA_Parser.get_flight_plan`? I suggest that you create a list of only those functions that the user would interact with. Everything else is "private" (not part of your module's "public API"). Once you have defined this, then you can organize your code to make it clear which functions are private and which are public. Then, you will want to add documentation (docstrings) for the public functions, so that the users know how to use them (there are many existing examples in para-atm that you can refer to).
> 
> Also, some of your files (such as `Reshape_Information_2.py`) do not actually define any functions, so it is unclear what their role is within para-atm. Potentially these are extraneous and can be removed from your submission. If they are required by your module, some re-organization will be needed.
> 
> Lastly, if you are new to git, I encourage you to read the first three chapters of the Git Book: https://git-scm.com/book/en/v2.

**Comment by yingying1968** [comment]
Hi，

Thank you for your help. I will check the naming request soon.

The purpose of the model to generate the real historical speed of each road
segment in the airport and import these real historical speeds into the
NATS ground simulation. In order to achieve the goal, I need to complete
the trajectory of each aircraft since some of them have missed trajectory.
I tried not to use "os" before, but the data of each aircraft is too huge
and can't be stored in the memory. If you have any suggestions on the data
store, please let me know.

Best,
Yanyu

jmcfarland-swri <notifications@github.com> 于2020年6月11日周四 下午3:35写道：

**Comment by yingying1968** [comment]
Hi:

Sure. Sorry that I am a beginner in coding. I may need a lot of help from
you to organize the code properly. If possible, would you please schedule a
meeting with me? I am free next Monday, Thursday, and Friday.

Thanks,
Yanyu

jmcfarland-swri <notifications@github.com> 于2020年6月11日周四 下午4:09写道：

**Comment by jmcfarland-swri** [comment]
If you are new to coding, it's not going to be practical to cover that in one phone call.  My suggestion would be to start by reading up on Python:

- https://docs.python.org/3.8/tutorial/index.html: at least through Ch. 7 (8 and 9 are also good to know)
- Then learn about numpy, which is the standard numerical library that is used in Python: https://cs231n.github.io/python-numpy-tutorial/ and https://numpy.org/devdocs/user/quickstart.html
- Matplotlib for plotting: https://matplotlib.org/ (works very similar to Matlab)
- pandas for working with data tables and more complex data structures: https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

This will give you a good foundation, and there is more project-specific information in the para-atm Guide to Contributing.  Once you get through all of this, then it will be easier to help you with specific questions.  It seems like a lot, but if you take it piece by piece, and if you work through and practice the examples yourself, you will be able to pick it up over time.

**Comment by yingying1968** [comment]
Hi,

Thank you for your suggestion. I will go through the materials that you
provided.

Thanks,
Yanyu

jmcfarland-swri <notifications@github.com> 于2020年6月11日周四 下午5:24写道：

**Pull request closed without merging**
